# See https://prettier.io/docs/en/options.html
useTabs: true
overrides:
  - files:
      - ".prettierrc"
      - ".lintstagedrc"
    options:
      parser: "yaml"
  - files:
      - ".sequelizerc"
    options:
      parser: "babel"
  - files:
    - "*.md"
    options:
      tabWidth: 2
      useTabs: false
