name: Deploy

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: actions/cache@v1 # safe for macOS and Ubuntu runners.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Fetch dependencies
        run: |
          npm ci
        env:
          NODE_ENV: ci # Because we need the devDependencies in order to build.

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Run post-build tests
        run: |
          npm run test-build

      - name: Get the publish registry
        # Remove this whenandif merge-release can read direcly from the package.json
        run: |
          echo "::set-env name=NPM_REGISTRY_URL::$(node -p "require('./package.json').publishConfig.registry")"

      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
