name: Deploy

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Fetch dependencies
        run: |
          npm ci
        env:
          NODE_ENV: ci # Because we need the devDependencies in order to build.

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Run post-build tests
        run: |
          npm run test-build

      - name: Clean up the packages
        env:
          NODE_ENV: production
        run: |
          npm prune

      - name: Install publishing tools
        run: |
          npm i -g \
          semantic-release@19 \
          ;

      - name: Get the publish registry
        id: registry
        run: |
          NPM_URL="$(jq -r '.publishConfig.registry' package.json)"
          echo "NPM_URL=${NPM_URL}"
          echo "::set-output name=NPM_URL::${NPM_URL}"

          NPM_SCOPE="$(jq -r '.name' package.json | sed -E 's;^(@[^/]+)/.*;\1;')"
          echo "NPM_SCOPE=${NPM_SCOPE}"
          echo "::set-output name=NPM_SCOPE::${NPM_SCOPE}"

      - uses: actions/setup-node@v3
        with:
          registry-url: ${{ steps.registry.outputs.NPM_URL }}
          scope: ${{ steps.registry.outputs.NPM_SCOPE }}

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
